name: ci
on: [push, pull_request]
permissions:
  contents: read
jobs:
  cache:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: ['1.85.0', stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo test --locked
      - run: cargo clippy --locked --all-targets -- -D warnings
      - run: cargo run --locked --release --example experiment
